trigger:
  - main

pool:
  vmImage: "windows-latest"

stages:
  - stage: Build
    displayName: "Build Stage"
    jobs:
      - job: Build
        displayName: "Build the Function App"
        steps:
          - task: UseDotNet@2
            inputs:
              packageType: "sdk"
              version: "6.x"
          - script: |
              dotnet restore
              dotnet build --configuration Release
            displayName: "Build Function App"

  - stage: Test
    displayName: "Test Stage"
    jobs:
      - job: Test
        displayName: "Run Unit Tests"
        steps:
          - script: |
              dotnet test --configuration Release
            displayName: "Run Unit Tests"
